### PR TITLE
Add "Minimized" condition to mute

### PR DESCRIPTION
**Pull request by lamrongol**
I added a "Mute Condition" setting.
When you select "Minimized", only minimized windows are muted, windows which are just only background aren't muted.

### CODE REVIEW

**Comment by nefares** [comment]
I have created a new branch for this feature. Please try out the changes I made to your code.

Not working is when a process has multiple windows. Only the "Main" window will be muted if minimized

**Comment by nefares** [comment]
[https://github.com/nefares/Background-Muter/tree/lamrongol-lamrongol-feature-add-minimized-condition](url)

**Comment by nefares** [comment]
@lamrongol let me know once you verify that this is the desired functionality/ if you have additional changes or comments

**Comment by lamrongol** [comment]
I can't push to your repository and sent pull request https://github.com/nefares/Background-Muter/pull/18
See detail.

**Pull request merged**
